import type { Metadata } from "next";

import Navigation from "@/components/Navigation/Navigation";

import styles from "../../styles/page.module.scss";

export const metadata: Metadata = {
  title: "?? NEW PORTFOLIO",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div className={styles.page}>
      <Navigation />
      <main>
        <h1>ABOUT PAGE</h1>
        <p>Body Copy here - Lorem ipsum odor amet, consectetuer adipiscing elit. Fringilla habitant class massa suscipit vel. Lectus nostra ad eu vestibulum sodales cursus turpis. Bibendum vel praesent vel dis ligula suscipit nisi. Habitasse in adipiscing mauris orci sagittis nisl pulvinar. Magnis phasellus class orci tortor commodo convallis neque. Nulla litora litora; platea dapibus vehicula orci.</p>
      </main>
    </div>
  );
}