import type { Metadata } from "next";

import Link from "@comp/Link/Link";
import Navigation from "@/components/Navigation/Navigation";

import styles from "../styles/page.module.scss";

export const metadata: Metadata = {
  title: "?? NEW PORTFOLIO",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className={styles.page}>
      <Navigation />
      <main>
        <h1>Katrina Cloyd</h1>
        <h2>Portfolio Site</h2>
        <h3>2025 Update -- Coming soon!</h3>
        <p>Body Copy here</p>
        <h4>Detail Text - Tools - Detail Info</h4>
        <Link text='External Test Link' url='/boop' external/>
        <h1>The Program</h1>
        <h4>Typescript - Next.js - Contentful - SASS</h4>
        <Link text='Internal Test Link' url='/boop'/>
        <h2>Test Subheading Here</h2>
        <p>Body Copy here - Lorem ipsum odor amet, consectetuer adipiscing elit. Fringilla habitant class massa suscipit vel. Lectus nostra ad eu vestibulum sodales cursus turpis. Bibendum vel praesent vel dis ligula suscipit nisi. Habitasse in adipiscing mauris orci sagittis nisl pulvinar. Magnis phasellus class orci tortor commodo convallis neque. Nulla litora litora; platea dapibus vehicula orci.</p>
        <p>Body Copy here - Lorem ipsum odor amet, consectetuer adipiscing elit. Fringilla habitant class massa suscipit vel. Lectus nostra ad eu vestibulum sodales cursus turpis. Bibendum vel praesent vel dis ligula suscipit nisi. Habitasse in adipiscing mauris orci sagittis nisl pulvinar. Magnis phasellus class orci tortor commodo convallis neque. Nulla litora litora; platea dapibus vehicula orci.</p>
        <p>Body Copy here - Lorem ipsum odor amet, consectetuer adipiscing elit. Fringilla habitant class massa suscipit vel. Lectus nostra ad eu vestibulum sodales cursus turpis. Bibendum vel praesent vel dis ligula suscipit nisi. Habitasse in adipiscing mauris orci sagittis nisl pulvinar. Magnis phasellus class orci tortor commodo convallis neque. Nulla litora litora; platea dapibus vehicula orci.</p>
        <p>Body Copy here - Lorem ipsum odor amet, consectetuer adipiscing elit. Fringilla habitant class massa suscipit vel. Lectus nostra ad eu vestibulum sodales cursus turpis. Bibendum vel praesent vel dis ligula suscipit nisi. Habitasse in adipiscing mauris orci sagittis nisl pulvinar. Magnis phasellus class orci tortor commodo convallis neque. Nulla litora litora; platea dapibus vehicula orci.</p>
        <h2 id='contact'>CONTACT SECTION HERE...! </h2>
        <p>Will make this section a component so it has the correct top-margin</p>
        <p>Body Copy here - Lorem ipsum odor amet, consectetuer adipiscing elit. Fringilla habitant class massa suscipit vel. Lectus nostra ad eu vestibulum sodales cursus turpis. Bibendum vel praesent vel dis ligula suscipit nisi. Habitasse in adipiscing mauris orci sagittis nisl pulvinar. Magnis phasellus class orci tortor commodo convallis neque. Nulla litora litora; platea dapibus vehicula orci.</p>
      </main>
    </div>
  );
}
